preload = /home/rathod-sahaab/Pictures/wallpapers/fern.jpg

wallpaper {
    monitor = eDP-1
    path = /home/rathod-sahaab/Pictures/wallpapers/fern.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = /home/rathod-sahaab/Pictures/wallpapers/fern.jpg
    fit_mode = cover
}


