preload = ~/Pictures/wallpapers/mountain-landscape-with-hot-air-balloon-dawn-generative-ai.jpg

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/mountain-landscape-with-hot-air-balloon-dawn-generative-ai.jpg
    fit_mode = cover
}
