gesture = 3, horizontal, workspace

gestures {
    workspace_swipe_distance = 150        # Lower value = greater sensitivity (default is 300)
    workspace_swipe_cancel_ratio = 0.1   # Lower value = easier to activate gesture (default is 0.5)
    workspace_swipe_min_speed_to_force = 3 # Lower = more likely to trigger gesture even slowly
}
