################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-1,preferred,auto,1.333333
monitor=DP-1,preferred,auto,auto,transform,1
monitor=DP-9,preferred,auto,auto,transform,3

