################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

# work
monitor=DP-1,preferred,0x0,1.333
monitor=DP-8,preferred,2880x-100,1,transform,3
monitor=DP-9,preferred,-1080x-100,1,transform,1

# Gaming
# monitor=DP-9,1920x1080,auto,1
workspace=1,monitor:DP-9
workspace=2,monitor:DP-1
workspace=3,monitor:DP-8
